/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Appointment {
  'id' : bigint,
  'status' : AppointmentStatus,
  'serviceType' : ServiceType,
  'projectDescription' : string,
  'name' : string,
  'createdAt' : bigint,
  'email' : string,
  'phone' : string,
  'dateTime' : string,
}
export interface AppointmentInput {
  'serviceType' : ServiceType,
  'projectDescription' : string,
  'name' : string,
  'email' : string,
  'phone' : string,
  'dateTime' : string,
}
export type AppointmentStatus = { 'cancelled' : null } |
  { 'pending' : null } |
  { 'confirmed' : null };
export type ExternalBlob = Uint8Array;
export type MediaType = { 'video' : null } |
  { 'link' : null };
export interface PortfolioItem {
  'id' : bigint,
  'url' : string,
  'title' : string,
  'serviceType' : ServiceType,
  'thumbnailUrl' : [] | [string],
  'createdAt' : bigint,
  'description' : string,
  'videoBlob' : [] | [ExternalBlob],
  'mediaType' : MediaType,
}
export interface PortfolioItemInput {
  'url' : string,
  'title' : string,
  'serviceType' : ServiceType,
  'thumbnailUrl' : [] | [string],
  'description' : string,
  'videoBlob' : [] | [ExternalBlob],
  'mediaType' : MediaType,
}
export interface Review {
  'id' : bigint,
  'serviceType' : ServiceType,
  'clientName' : string,
  'createdAt' : bigint,
  'reviewText' : string,
  'rating' : bigint,
}
export interface ReviewInput {
  'serviceType' : ServiceType,
  'clientName' : string,
  'reviewText' : string,
  'rating' : bigint,
}
export type ServiceType = { 'videoEditing' : null } |
  { 'webAppDev' : null } |
  { 'uiUxDesign' : null } |
  { 'graphicsDesign' : null };
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _ImmutableObjectStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _ImmutableObjectStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _ImmutableObjectStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_immutableObjectStorageBlobsAreLive' : ActorMethod<
    [Array<Uint8Array>],
    Array<boolean>
  >,
  '_immutableObjectStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_immutableObjectStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_immutableObjectStorageCreateCertificate' : ActorMethod<
    [string],
    _ImmutableObjectStorageCreateCertificateResult
  >,
  '_immutableObjectStorageRefillCashier' : ActorMethod<
    [[] | [_ImmutableObjectStorageRefillInformation]],
    _ImmutableObjectStorageRefillResult
  >,
  '_immutableObjectStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControl' : ActorMethod<[], undefined>,
  'addPortfolioItem' : ActorMethod<
    [PortfolioItemInput],
    { 'ok' : bigint } |
      { 'err' : string }
  >,
  'addReview' : ActorMethod<
    [ReviewInput],
    { 'ok' : bigint } |
      { 'err' : string }
  >,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'deletePortfolioItem' : ActorMethod<
    [bigint],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'deleteReview' : ActorMethod<[bigint], { 'ok' : null } | { 'err' : string }>,
  'getAppointments' : ActorMethod<[], Array<Appointment>>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getPortfolioByService' : ActorMethod<[ServiceType], Array<PortfolioItem>>,
  'getPortfolioItems' : ActorMethod<[], Array<PortfolioItem>>,
  'getReviews' : ActorMethod<[], Array<Review>>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'submitAppointment' : ActorMethod<
    [AppointmentInput],
    { 'ok' : bigint } |
      { 'err' : string }
  >,
  'updateAppointmentStatus' : ActorMethod<
    [bigint, AppointmentStatus],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'updatePortfolioItem' : ActorMethod<
    [bigint, PortfolioItemInput],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'updateReview' : ActorMethod<
    [bigint, ReviewInput],
    { 'ok' : null } |
      { 'err' : string }
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];