/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _ImmutableObjectStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _ImmutableObjectStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const ServiceType = IDL.Variant({
  'videoEditing' : IDL.Null,
  'webAppDev' : IDL.Null,
  'uiUxDesign' : IDL.Null,
  'graphicsDesign' : IDL.Null,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const MediaType = IDL.Variant({ 'video' : IDL.Null, 'link' : IDL.Null });
export const PortfolioItemInput = IDL.Record({
  'url' : IDL.Text,
  'title' : IDL.Text,
  'serviceType' : ServiceType,
  'thumbnailUrl' : IDL.Opt(IDL.Text),
  'description' : IDL.Text,
  'videoBlob' : IDL.Opt(ExternalBlob),
  'mediaType' : MediaType,
});
export const ReviewInput = IDL.Record({
  'serviceType' : ServiceType,
  'clientName' : IDL.Text,
  'reviewText' : IDL.Text,
  'rating' : IDL.Nat,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const AppointmentStatus = IDL.Variant({
  'cancelled' : IDL.Null,
  'pending' : IDL.Null,
  'confirmed' : IDL.Null,
});
export const Appointment = IDL.Record({
  'id' : IDL.Nat,
  'status' : AppointmentStatus,
  'serviceType' : ServiceType,
  'projectDescription' : IDL.Text,
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'email' : IDL.Text,
  'phone' : IDL.Text,
  'dateTime' : IDL.Text,
});
export const PortfolioItem = IDL.Record({
  'id' : IDL.Nat,
  'url' : IDL.Text,
  'title' : IDL.Text,
  'serviceType' : ServiceType,
  'thumbnailUrl' : IDL.Opt(IDL.Text),
  'createdAt' : IDL.Int,
  'description' : IDL.Text,
  'videoBlob' : IDL.Opt(ExternalBlob),
  'mediaType' : MediaType,
});
export const Review = IDL.Record({
  'id' : IDL.Nat,
  'serviceType' : ServiceType,
  'clientName' : IDL.Text,
  'createdAt' : IDL.Int,
  'reviewText' : IDL.Text,
  'rating' : IDL.Nat,
});
export const AppointmentInput = IDL.Record({
  'serviceType' : ServiceType,
  'projectDescription' : IDL.Text,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'phone' : IDL.Text,
  'dateTime' : IDL.Text,
});

export const idlService = IDL.Service({
  '_immutableObjectStorageBlobsAreLive' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [IDL.Vec(IDL.Bool)],
      ['query'],
    ),
  '_immutableObjectStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_immutableObjectStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_ImmutableObjectStorageCreateCertificateResult],
      [],
    ),
  '_immutableObjectStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
      [_ImmutableObjectStorageRefillResult],
      [],
    ),
  '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControl' : IDL.Func([], [], []),
  'addPortfolioItem' : IDL.Func(
      [PortfolioItemInput],
      [IDL.Variant({ 'ok' : IDL.Nat, 'err' : IDL.Text })],
      [],
    ),
  'addReview' : IDL.Func(
      [ReviewInput],
      [IDL.Variant({ 'ok' : IDL.Nat, 'err' : IDL.Text })],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deletePortfolioItem' : IDL.Func(
      [IDL.Nat],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'deleteReview' : IDL.Func(
      [IDL.Nat],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'getAppointments' : IDL.Func([], [IDL.Vec(Appointment)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getPortfolioByService' : IDL.Func(
      [ServiceType],
      [IDL.Vec(PortfolioItem)],
      ['query'],
    ),
  'getPortfolioItems' : IDL.Func([], [IDL.Vec(PortfolioItem)], ['query']),
  'getReviews' : IDL.Func([], [IDL.Vec(Review)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'submitAppointment' : IDL.Func(
      [AppointmentInput],
      [IDL.Variant({ 'ok' : IDL.Nat, 'err' : IDL.Text })],
      [],
    ),
  'updateAppointmentStatus' : IDL.Func(
      [IDL.Nat, AppointmentStatus],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'updatePortfolioItem' : IDL.Func(
      [IDL.Nat, PortfolioItemInput],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'updateReview' : IDL.Func(
      [IDL.Nat, ReviewInput],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _ImmutableObjectStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _ImmutableObjectStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const ServiceType = IDL.Variant({
    'videoEditing' : IDL.Null,
    'webAppDev' : IDL.Null,
    'uiUxDesign' : IDL.Null,
    'graphicsDesign' : IDL.Null,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const MediaType = IDL.Variant({ 'video' : IDL.Null, 'link' : IDL.Null });
  const PortfolioItemInput = IDL.Record({
    'url' : IDL.Text,
    'title' : IDL.Text,
    'serviceType' : ServiceType,
    'thumbnailUrl' : IDL.Opt(IDL.Text),
    'description' : IDL.Text,
    'videoBlob' : IDL.Opt(ExternalBlob),
    'mediaType' : MediaType,
  });
  const ReviewInput = IDL.Record({
    'serviceType' : ServiceType,
    'clientName' : IDL.Text,
    'reviewText' : IDL.Text,
    'rating' : IDL.Nat,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const AppointmentStatus = IDL.Variant({
    'cancelled' : IDL.Null,
    'pending' : IDL.Null,
    'confirmed' : IDL.Null,
  });
  const Appointment = IDL.Record({
    'id' : IDL.Nat,
    'status' : AppointmentStatus,
    'serviceType' : ServiceType,
    'projectDescription' : IDL.Text,
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'email' : IDL.Text,
    'phone' : IDL.Text,
    'dateTime' : IDL.Text,
  });
  const PortfolioItem = IDL.Record({
    'id' : IDL.Nat,
    'url' : IDL.Text,
    'title' : IDL.Text,
    'serviceType' : ServiceType,
    'thumbnailUrl' : IDL.Opt(IDL.Text),
    'createdAt' : IDL.Int,
    'description' : IDL.Text,
    'videoBlob' : IDL.Opt(ExternalBlob),
    'mediaType' : MediaType,
  });
  const Review = IDL.Record({
    'id' : IDL.Nat,
    'serviceType' : ServiceType,
    'clientName' : IDL.Text,
    'createdAt' : IDL.Int,
    'reviewText' : IDL.Text,
    'rating' : IDL.Nat,
  });
  const AppointmentInput = IDL.Record({
    'serviceType' : ServiceType,
    'projectDescription' : IDL.Text,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'phone' : IDL.Text,
    'dateTime' : IDL.Text,
  });
  
  return IDL.Service({
    '_immutableObjectStorageBlobsAreLive' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [IDL.Vec(IDL.Bool)],
        ['query'],
      ),
    '_immutableObjectStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_immutableObjectStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_ImmutableObjectStorageCreateCertificateResult],
        [],
      ),
    '_immutableObjectStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
        [_ImmutableObjectStorageRefillResult],
        [],
      ),
    '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControl' : IDL.Func([], [], []),
    'addPortfolioItem' : IDL.Func(
        [PortfolioItemInput],
        [IDL.Variant({ 'ok' : IDL.Nat, 'err' : IDL.Text })],
        [],
      ),
    'addReview' : IDL.Func(
        [ReviewInput],
        [IDL.Variant({ 'ok' : IDL.Nat, 'err' : IDL.Text })],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deletePortfolioItem' : IDL.Func(
        [IDL.Nat],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'deleteReview' : IDL.Func(
        [IDL.Nat],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'getAppointments' : IDL.Func([], [IDL.Vec(Appointment)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getPortfolioByService' : IDL.Func(
        [ServiceType],
        [IDL.Vec(PortfolioItem)],
        ['query'],
      ),
    'getPortfolioItems' : IDL.Func([], [IDL.Vec(PortfolioItem)], ['query']),
    'getReviews' : IDL.Func([], [IDL.Vec(Review)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'submitAppointment' : IDL.Func(
        [AppointmentInput],
        [IDL.Variant({ 'ok' : IDL.Nat, 'err' : IDL.Text })],
        [],
      ),
    'updateAppointmentStatus' : IDL.Func(
        [IDL.Nat, AppointmentStatus],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'updatePortfolioItem' : IDL.Func(
        [IDL.Nat, PortfolioItemInput],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'updateReview' : IDL.Func(
        [IDL.Nat, ReviewInput],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };